### ISSUE TITLE
how can I contribute?

### ISSUE THREAD

**Issue by rain1024** [electronut/tp10#1]
Hi electronut, your project is interesting. My daughter will come to our world in April 2016.

How can I contribute to your project?

PS: I try to do third assignment with p5js here

http://codepen.io/rain1024/pen/EPEMYK

**Comment by electronut** [comment]
Hello,

Congratulations, and I wish you the very best for your daughter's arrival.

At this point what would help me is getting the word out. You can follow me
on twitter where I will post new exercises every week:

https://twitter.com/electronutLabs

Thanks!

Mahesh Venkitachalam
electronut.in

**Comment by rain1024** [comment]
okay.

**Comment by ramkameswaran** [comment]
Hi Mahesh,
I got a Raspberry Pi3 for my 11 years old nephew who is visiting us from US (we are in Canada). I found your book "Python Playground : Geeky Projects for the Curious Programmer" on EBSCO and had a preview. Thank you for providing these very interesting projects. I am planning to use these to teach him Python.

**Comment by electronut** [comment]
Hello @ramkameswaran,

Very happy to hear it. Good luck!

Regards
